name: Integration Tests

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      # Load OS-pass env via a step
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Load secrets from OS Pass or GitHub Secrets
        run: |
          echo "Пробуем загрузить секреты из pass"
          if pass show personal-productivity-ai/env > .env; then
            echo "Секреты загружены из pass"
          else
            echo "pass не доступен, используем GitHub Secrets"
            echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
            echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
          fi
        shell: bash

      - name: Run Integration Tests
        run: npm run test:integration

      - name: Upload Test Results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-results
          path: tests/integration/**/coverage/**/*
