name: 📊 Monitor Production

on:
  schedule:
    # Запуск каждые 5 минут
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      check_type:
        description: 'Type of check to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - health
          - performance
          - security

env:
  NODE_VERSION: '18'
  PRODUCTION_URL: 'https://personal-productivity-ai.vercel.app'

jobs:
  # 🏥 Health check
  health-check:
    name: 🏥 Health Check
    runs-on: ubuntu-latest
    if: github.event.inputs.check_type == 'all' || github.event.inputs.check_type == 'health' || github.event_name == 'schedule'
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🏥 Check API health
        run: |
          echo "Checking API health..."
          curl -f -s -o /dev/null -w "%{http_code}" "${{ env.PRODUCTION_URL }}/api/test" || exit 1

      - name: 🏥 Check main page
        run: |
          echo "Checking main page..."
          curl -f -s -o /dev/null -w "%{http_code}" "${{ env.PRODUCTION_URL }}" || exit 1

      - name: 🏥 Check planner page
        run: |
          echo "Checking planner page..."
          curl -f -s -o /dev/null -w "%{http_code}" "${{ env.PRODUCTION_URL }}/planner" || exit 1

  # ⚡ Performance check
  performance-check:
    name: ⚡ Performance Check
    runs-on: ubuntu-latest
    if: github.event.inputs.check_type == 'all' || github.event.inputs.check_type == 'performance' || github.event_name == 'schedule'
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: ⚡ Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.12.x
          lhci autorun --collect.url="${{ env.PRODUCTION_URL }}" --collect.url="${{ env.PRODUCTION_URL }}/planner"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

  # 🔒 Security check
  security-check:
    name: 🔒 Security Check
    runs-on: ubuntu-latest
    if: github.event.inputs.check_type == 'all' || github.event.inputs.check_type == 'security' || github.event_name == 'schedule'
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔒 Run security audit
        run: npm audit --audit-level high

      - name: 🔍 Check for known vulnerabilities
        run: |
          echo "Checking for known vulnerabilities..."
          npm audit --audit-level moderate

  # 📊 Generate report
  generate-report:
    name: 📊 Generate Report
    runs-on: ubuntu-latest
    needs: [health-check, performance-check, security-check]
    if: always()
    steps:
      - name: 📊 Generate monitoring report
        run: |
          echo "## 📊 Production Monitoring Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🏥 Health Check" >> $GITHUB_STEP_SUMMARY
          echo "Status: ${{ needs.health-check.result == 'success' && '✅ Healthy' || '❌ Unhealthy' }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### ⚡ Performance Check" >> $GITHUB_STEP_SUMMARY
          echo "Status: ${{ needs.performance-check.result == 'success' && '✅ Good' || '❌ Issues' }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🔒 Security Check" >> $GITHUB_STEP_SUMMARY
          echo "Status: ${{ needs.security-check.result == 'success' && '✅ Secure' || '❌ Vulnerabilities' }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📅 Timestamp" >> $GITHUB_STEP_SUMMARY
          echo "Generated: $(date)" >> $GITHUB_STEP_SUMMARY

  # 🚨 Alert on issues
  alert:
    name: 🚨 Alert on Issues
    runs-on: ubuntu-latest
    needs: [health-check, performance-check, security-check]
    if: always() && (needs.health-check.result == 'failure' || needs.performance-check.result == 'failure' || needs.security-check.result == 'failure')
    steps:
      - name: 🚨 Send alert
        run: |
          echo "🚨 Production monitoring detected issues!"
          echo "Health: ${{ needs.health-check.result }}"
          echo "Performance: ${{ needs.performance-check.result }}"
          echo "Security: ${{ needs.security-check.result }}"
          # Здесь можно добавить отправку уведомлений в Slack, Discord, email и т.д.
